from temperature.temperature import Temperature
from ConfigurationLoader.AutoGenerated import AutoGenerated
from temperature.mqttproxy import MqttProxy
import datetime;

class MqttTemperature(AutoGenerated, Temperature):
    def __init__(self, config = None, topic = None, updateFunc = None):
        super().__init__()
        self.mqtt_ = MqttProxy()
        self.temperature_ = float('nan')
        self.updateFunc_ = updateFunc
        self.classFinder = {"topic": self.setTopic}

        if(topic):
            self.setTopic(topic)
        elif(config):
            self.loadConfig(config)

        self.subscribe()

    def subscribe(self):
        self.mqtt_.subscribeToTopic(self.topic_, self.updateTemperature)
        print("will sign function ", self.updateTemperature)

    def setTopic(self, config):
        self.topic_ = config

    def updateTemperature(self, temp):
        print("updateTemperature ", self, " with: ", temp)
        self.temperature_ = float(temp)
        self.timestamp_ = datetime.datetime.now().timestamp()

        if (self.updateFunc_ is not None):
            self.updateFunc_()

    def get(self):
        return self.temperature_

    def getTime(self):
        return self.timestamp_


if __name__ == "__main__":
    host = "mqtt.tinker.haus"
    port = 1883

    def updatefunc():
        print ("needchangenow !!\n")

    mqttBroker = MqttProxy(host, port)

    m1 = MqttTemperature("raspberry-sensor-dev/temperature/current", updateFunc = updatefunc)
    m2 = MqttTemperature("raspberry-sensor-dev/humidity/current", updateFunc = updatefunc)


    while True:
        import time

        print("Temperature 1 is ", m1.get())
        print("Temperature 2 is ", m2.get())

        time.sleep(1)
