from ConfigurationLoader.AutoGenerated import AutoGenerated
from temperature.DaikinTemperature import DaikinTemperature
from temperature.mqtttemperature   import MqttTemperature
from tigger.trigger import Trigger

import logging

class TemperatureGroup(Trigger, AutoGenerated):
    def __init__(self, config):
        AutoGenerated.__init__(self)
        self.logger = logging.getLogger(self.__class__.__name__)
        print(config)

        self.classFinder = {"mqtt": MqttTemperature,
                            "daikin" : DaikinTemperature}

        self.children = self.loadListConfig(config)

        self.registerCallback(self.children, self.propagate)

    def __str__(self):
        return "Temperature group to unify input gathering"
