from ConfigurationLoader.AutoGenerated import AutoGenerated
from temperature.DaikinTemperature import DaikinTemperature
from temperature.mqtttemperature   import MqttTemperature


class TemperatureGroup(AutoGenerated):
    def __init__(self, config):
        super().__init__()
        print(config)

        self.classFinder = {"mqtt": MqttTemperature,
                            "daikin" : DaikinTemperature}

        self.children = self.loadListConfig(config)

        for sensor in self.children:
            sensor.setCallback(self.waterfallCallback)

    def __str__(self):
        return "Temperature group to unify input gathering"

    def waterfallCallback(self, temp):
        print ("Waterfall temperature: " + str(temp))
