from ConfigurationLoader.Parser import Parser
from ConfigurationLoader.AutoGenerated import AutoGenerated

from thermostate.thermostategroup import ThermostateGroup
from temperature.mqttproxy import MqttProxy

import time

class HeatMaster(AutoGenerated):

    def __init__(self, config = None):
        super().__init__()

        print (self.classFinder)

        self.classFinder = {"mqtt": MqttProxy, "thermostates" : ThermostateGroup}

        if(config):
            self.children = self.loadConfig(config)

        print ("------------------------------------------- INSPECT START TIME ----------------------------------------------")
        self.inspect()
        print ("-------------------------------------------- INSPECT END TIME -----------------------------------------------")

if __name__ == "__main__":
    import sys
    confFile = sys.argv[1]
    ps = Parser(confFile)

    hm = HeatMaster(config = ps.getConfiguration())

    while True:
        time.sleep(1)
