import sys
print(sys.path)

from mock import Mock
sys.modules['RPi'] = Mock()
sys.modules['RPi.GPIO'] = Mock()

import RPi.GPIO

from ConfigurationLoader.Parser import Parser
from ConfigurationLoader.AutoGenerated import AutoGenerated

from thermostate.thermostategroup import ThermostateGroup
from temperature.mqttproxy import MqttProxy
from heater.heater import Heater
from tigger.trigger import Trigger
from threading import Event

from heatmaster import HeatMaster

import time
import logging

import utils.ColoredLogger

import unittest


class BasicTest(unittest.TestCase):
    def test_BasicTest(self):
        import sys
        import os
        absFilePath = os.path.abspath(__file__)
        path, filename = os.path.split(absFilePath)
        confFile = path + "/config-test-simple.json"

        print("Mocked gpio 31 is {}".format(RPi.GPIO.input(31)))

        utils.ColoredLogger.setColoredLogger()

        ps = Parser(confFile)
        hm = HeatMaster(config = ps.getConfiguration())
        hm.run(5)
