from ConfigurationLoader.Parser import Parser
from ConfigurationLoader.AutoGenerated import AutoGenerated

from thermostate.thermostategroup import ThermostateGroup
from temperature.mqttproxy import MqttProxy
from heater.heater import Heater
from tigger.trigger import Trigger
from threading import Event

from heatmaster import HeatMaster

import time
import logging

import utils.ColoredLogger

import unittest

class Whatever(unittest.TestCase):
    def test_runwhatever(self):
        import sys
        confFile = "./test/config-test-simple.json"

        utils.ColoredLogger.setColoredLogger()

        ps = Parser(confFile)
        hm = HeatMaster(config = ps.getConfiguration())
        hm.run(5)
