

class AutoGenerated():
    def __init__(self):
        self.classFinder = {}

    def loadListConfig(self, listConfig):
        members = []
        print(listConfig)
        for item in listConfig:
            group = self.loadConfig(item)
            members.append (group)
        return members

    def loadConfig(self, config):
        print(config)
        members = []
        for k, v in config.items():
            print (" Key: ", k, " : ", v)
            keyClass = self.classFinder[k]
            print (keyClass)

            o = keyClass(config = v)
            if (o):
                members.append(o)
        print (members)

        return members
