
class AutoGenerated():
    def __init__():
        self.classFinder = {}

        if(config):
            self.loadConfig(config)

    def loadListConfig(self, listConfig):
        print(listConfig)
        for item in listConfig:
            self.loadConfig(item)


    def loadConfig(self, config):
        print(config)

        for k, v in config.items():
            print (" Key: ", k, " : ", v)
            keyClass = self.classFinder[k]
            print (keyClass)

            o = keyClass(config = v)
