from heatmaster.ConfigurationLoader.AutoGenerated import AutoGenerated
from heatmaster.heater.mqttheater import MqttHeater
from heatmaster.utils.trigger import Trigger


class Heater(Trigger, AutoGenerated):
    def __init__(self, config=None):
        AutoGenerated.__init__(self)

        self.classFinder = {
            "mqtt": MqttHeater,
        }

        self.children = self.loadConfig(config)
        self.registerCallback(self.children, self.propagate)

    def __str__(self):
        return "Heater Group"
