from relay.relay import Relay
from temperature.temperaturefactory import TemperatureFactory
from ConfigurationLoader.AutoGenerated import AutoGenerated

from relay.relay import Relay

class Thermostate(AutoGenerated):

    def __init__(self, config = None):
        self.classFinder = {"name": self.setName,
                            "relay" : Relay,
                            "temperature" : TemperatureFactory}

        print (" This is a thermostate !!! ")
        print (" I AM ALIVE !! ")

        self.loadListConfig(config)

    def setName(self, config):
        self.name_ = config
