from relay.relay import Relay
from temperature.temperaturegroup import TemperatureGroup
from ConfigurationLoader.AutoGenerated import AutoGenerated

class Thermostate(AutoGenerated):

    def __init__(self, config = None):
        super().__init__()
        self.classFinder = {"name": self.setName,
                            "relay" : Relay,
                            "temperature" : TemperatureGroup}

        print (" This is a thermostate !!! ")
        print (" I AM ALIVE !! ")

        self.children = self.loadConfig(config)

    def __str__(self):
        return "Thermostate " + self.name_

    def setName(self, config):
        self.name_ = config
