from heatmaster.thermostate.thermostate import Thermostate
from heatmaster.ConfigurationLoader.AutoGenerated import AutoGenerated
from heatmaster.utils.trigger import Trigger

from heatmaster.utils import logging
logger = logging.getLogger(__name__)


class ThermostateGroup(Trigger, AutoGenerated):

    def __init__(self, config=None):
        AutoGenerated.__init__(self)
        Trigger.__init__(self)

        logger.info("ThermostateGroup config: " + str(config))
        logger.info("######### This is a thermostate GROUP START #########")

        self.children = self.loadItemization(config, Thermostate)
        self.registerCallback(self.children, self.propagate)

        logger.info("######### This is a thermostate GROUP  END  #########")

    def __str__(self):
        return "Thermostate group to unify control"
