from thermostate.thermostate import Thermostate
from ConfigurationLoader.AutoGenerated import AutoGenerated

class ThermostateGroup(AutoGenerated):

    def __init__(self, config = None):
        super().__init__()

        print ("ThermostateGroup config: ", config)

        print (" ################# This is a thermostate GROUP START ############## ")
        self.children = self.loadItemization(config, Thermostate)
        print (" ################## This is a thermostate GROUP END ############### ")

    def __str__(self):
        return "Thermostate group to unify control"
