from relay.relay import Relay
from temperature.temperaturegroup import TemperatureGroup
from ConfigurationLoader.AutoGenerated import AutoGenerated
from tigger.trigger import Trigger

import logging

class Thermostate(Trigger, AutoGenerated):

    def __init__(self, config = None):
        AutoGenerated.__init__(self)
        Trigger.__init__(self)
        self.logger = logging.getLogger(self.__class__.__name__)

        self.classFinder = {"name": self.setName,
                            "relay" : Relay,
                            "temperature" : TemperatureGroup}

        self.logger.info (" This is a thermostate !!! ")
        self.logger.info (" I AM ALIVE !! ")

        self.children = self.loadConfig(config)

        self.registerCallback(self.children, self.propagate)

    def __str__(self):
        return "Thermostate " + self.name_

    def setName(self, config):
        self.name_ = config
